[build]
  command = "cd /opt/build/repo && npm install --production=false && ./node_modules/.bin/vite build"
  publish = "dist"
  node_version = "18"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_BUILD_MODE = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 